### ISSUE TITLE
[DIVIDA] Adicionar funcionalidades na descrição de notificações privadas

### ISSUE THREAD

**Issue by stefanesouza** [fga-eps-mds/2018.2-CarDefense#112]
Eu, como desenvolvedor, desejo adicionar funcionalidades na descrição de uma notificação para melhorar o uso.

## Critérios de Aceitação
- [ ] Testes passando pelo ambiente
- [ ] Funcionalidades = adicionar foto
- [ ] Tornar visível para o usuário os erros de validação e quais campos são obrigatórios

**Comment by darmsDD** [comment]
Acho que isso pode ser utlizado na parte de inserir imagens para descrever o evento.
https://facebook.github.io/react-native/docs/images#uri-data-images
