### ISSUE TITLE
Organizar o feed das notificações 

### ISSUE THREAD

**Issue by stefanesouza** [fga-eps-mds/2018.2-CarDefense#114]
Eu, como desenvolvedor, desejo organizar o feed de forma mais intuitiva para o fácil uso do usuário.

## Critérios de aceitação
- [ ] Testes passando pelo ambiente de validação

## Comentário
- Organização do feed será a mesma para os dois tipos de notificação

**Comment by stefanesouza** [comment]
Pensei em algo assim, pode ou não ter esse botão de leia mais. Estudar o que é melhor para usabilidade.
![exemplo](https://user-images.githubusercontent.com/17994305/46645337-de304280-cb5a-11e8-99cf-648181db3754.png)

**Comment by bielrossi15** [comment]
O usuario vai realmente ficar vendo em que perfil estara logado no feed?
