### ISSUE TITLE
CRUD de Carros

### ISSUE THREAD

**Issue by stefanesouza** [fga-eps-mds/2018.2-CarDefense#115]
Eu, como desenvolvedor, desejo fazer um cadastro (adicionar, editar e deletar) do carro do usuário para coletar dados.

## Tasks
- [x] Testes
- [x] Precisa ter funcionalidades de: Criar, editar e deletar um carro
- [x] Ter validações dos campos e dizer quais são obrigatórios

## Comentário

**Comment by stefanesouza** [comment]
Sobre a validação:
![formbuilder-1900x700_c](https://user-images.githubusercontent.com/17994305/46645717-9ad6d380-cb5c-11e8-971d-2bed38d30e45.png)

**Comment by bielrossi15** [comment]
Sobre os campos que vamos usar pro cadastro, o campo obrigatório seria apenas a placa?
