### ISSUE TITLE
Criar perfil do usuário

### ISSUE THREAD

**Issue by stefanesouza** [fga-eps-mds/2018.2-CarDefense#116]
Eu, como desenvolvedor, desejo criar perfil do usuário para que o mesmo possa monitorar e configurar suas informações.

## Tasks
- [x] Testes

## Comentário

**Comment by stefanesouza** [comment]
Sugestão de tela:
![exemplo](https://user-images.githubusercontent.com/17994305/46645896-78918580-cb5d-11e8-9db4-b4827381ddba.png)

**Comment by bielrossi15** [comment]
A foto seria a do proprio usuario?
