### ISSUE TITLE
Aplicar Identidade Visual 

### ISSUE THREAD

**Issue by stefanesouza** [fga-eps-mds/2018.2-CarDefense#118]
Eu, como desenvolvedor, desejo ajustar o app para a identidade visual estabelecida para seguir o padrão de cores e fontes do produto.

## Critérios de Aceitação
- Cores e fontes definidas nesse link:

**Comment by lievertom** [comment]
Não há link para acessar a identidade visual.

**Comment by stefanesouza** [comment]
[Clique aqui para visualizar a Identidade Visual](https://docs.google.com/presentation/d/e/2PACX-1vR4w0zOqkJZW2CXKQIS69aUwFMTDR712eOW2soYBcZUjZZcvJ_0W2-jhCQSuBRjG0gl4a006JoxE4q7/pub?start=false&loop=false&delayms=3000)
