### ISSUE TITLE
Criar e constantemente evoluir o Documento de Visão do projeto

### ISSUE THREAD

**Issue by flyerjohn** [fga-eps-mds/2018.2-CarDefense#12]
## Descrição da Tarefa
É necessário que a equipe de desenvolvimento crie um documento de visão do projeto para poder entender o projeto.

## Critérios de Aceitação
- [ ] - Revisão constante do documento por toda equipe do projeto.

## Comentários Importantes

Esse documento é atualizado com o andamento do projeto por isso não tem uma pontuação nem sprint definidas.

**Comment by stefanesouza** [comment]
Materiais sugeridos por EPS para estudo: 
https://www.ibm.com/support/knowledgecenter/pt-br/SSWMEQ_4.0.6/com.ibm.rational.rrm.help.doc/topics/r_vision_doc.html

**Comment by stefanesouza** [comment]
Observação: Esse documento será atualizado ao longo do projeto. Sempre passando pelo seu critério de aceitação.

**Comment by lucassoaresouza** [comment]
Essa issue foi absorvida pela issue: [Realizar a refatoração de documentos para a release 2](https://github.com/fga-eps-mds/2018.2-CarDefense/issues/172)
