### ISSUE TITLE
Estudar maneiras para fazer a integração do APP com o Facebook

### ISSUE THREAD

**Issue by lucassoaresouza** [fga-eps-mds/2018.2-CarDefense#129]

**Comment by tayh** [comment]
ALguns links que podem ajudar nos estudos:
https://developers.facebook.com/docs/react-native/login/
https://developers.facebook.com/docs/facebook-login/overview/

**Comment by lucassoaresouza** [comment]
Show! Valeu, @tayh

**Comment by PauloVitorRocha** [comment]
https://developers.facebook.com/docs/plugins/share-button/
encontrei esse que seria mais especifico pro nosso problema
