### ISSUE TITLE
Criar e constantemente evoluir o Documento de Arquitetura do Projeto

### ISSUE THREAD

**Issue by PauloVitorRocha** [fga-eps-mds/2018.2-CarDefense#13]
## Descrição da Tarefa
É necessário que a equipe de desenvolvimento crie um documento de arquitetura do projeto para obter a visão geral da arquitetura abrangente o sistema.

## Critérios de Aceitação
- [ ] Revisão (constante) do Documento pelo papel de Arquiteto do projeto

## Comentários Importantes

Esse documento é atualizado com o andamento do projeto por isso não tem uma pontuação nem sprint definidas.

**Comment by darmsDD** [comment]
Diagrama de casos de uso feito. Sujeito a alterações se necessário.

**Comment by PauloVitorRocha** [comment]
Descrição dos casos de uso realizada. Sujeito a alterações se necessário.

**Comment by stefanesouza** [comment]
Materiais sugeridos por EPS para estudo:
http://www.funpar.ufpr.br:8080/rup/webtmpl/templates/a_and_d/rup_sad.htm
http://www.funpar.ufpr.br:8080/rup/process/artifact/ar_sadoc.htm

**Comment by stefanesouza** [comment]
Observação: Esse documento será atualizado ao longo do projeto. Sempre passando pelo seu critério de aceitação.

**Comment by lievertom** [comment]
Alteração no diagrama de casos de uso

**Comment by flyerjohn** [comment]
A base do diagrama de classes está sendo montada, atenção na atualização do doc

**Comment by rjoao** [comment]
Alteração no diagrama de casos de uso - Decomposição em diagramas menores.

**Comment by rjoao** [comment]
Indico o site https://yuml.me/ para a produção de diagramas de casos de uso, diagramas de classes e diagramas de atividades.

**Comment by mateusvroriz** [comment]
Criação do diagrama de React/Redux/Microsserviços

**Comment by lucassoaresouza** [comment]
Essa issue foi absorvida pela issue: [Realizar a refatoração de documentos para a release 2](https://github.com/fga-eps-mds/2018.2-CarDefense/issues/172)
