### ISSUE TITLE
Criar um novo sistema de homologação usando a nova assinatura de máquina virtual

### ISSUE THREAD

**Issue by lucassoaresouza** [fga-eps-mds/2018.2-CarDefense#130]
## Descrição da Tarefa
Criar um sistema para subir o ambiente de homologação do sistema na nova assinatura do azure

## Critérios de Aceitação

- [x] Criar a maquina virtual no azure
- [x] Subir o sistema de homologação na nova maquina

**Comment by mateusvroriz** [comment]
A maquina virtual para o sistema de homologação foi criada e está configurada para uso.

**Comment by mateusvroriz** [comment]
O sistema de homologação foi instaurado na nova maquina criada
