### ISSUE TITLE
Repositório Open Source

### ISSUE THREAD

**Issue by mateusvroriz** [fga-eps-mds/2018.2-CarDefense#14]
## Descrição da Tarefa
Por causa do projeto ser em código aberto é necessário que se adeque o repositório do mesmo às regras de software open source.

## Critérios de Aceitação

- [X] Desciption
- [X] README
- [x] Code of Conduct
- [X] Contribuiting
- [X] License
- [X] Issues Templates
- [X] Pull Request Template

**Comment by lucassoaresouza** [comment]
Falta fazer a migração do docs para o github pages
