### ISSUE TITLE
US17 - Fazer login com facebook 

### ISSUE THREAD

**Issue by stefanesouza** [fga-eps-mds/2018.2-CarDefense#152]
## Descrição
Eu, como usuário, desejo poder entrar no aplicativo pelo Facebook pois facilita o uso e integração com o grupo.

## Tarefas
- [x] Colocar o botão de login o Facebook na tela de registro do app;
- [x] Após o login, o usuário deve ser redirecionado à tela inicial;

## Critérios de Aceitação
- [x] Fazer as validações de campo/usuário, se necessário;
- [ ] Funcionalidade testada;

**Comment by lievertom** [comment]
login do facebook utilizando o expo: https://docs.expo.io/versions/latest/sdk/facebook
