### ISSUE TITLE
US22 - Deletar carro

### ISSUE THREAD

**Issue by lievertom** [fga-eps-mds/2018.2-CarDefense#165]
## Descrição
Eu, como usuário, desejo ter um botão para deletar um carro. 

## Tarefas
 

- [x] Criar botão de deletar;
- [x] Criar função de deletar carro no back-end;

## Critérios de Aceitação

- [x] Ao clicar no botão deletar o carro, o mesmo deve ser retirado da lista de carros.

**Comment by darmsDD** [comment]
Qual será a cor botão?
