### ISSUE TITLE
Criar Pagina Inicial no pages 

### ISSUE THREAD

**Issue by mateusvroriz** [fga-eps-mds/2018.2-CarDefense#17]
## Descrição da Tarefa do projeto.

É necessário que haja uma página inicial no pages para que a partir dela se possa acessar todos os outros documentos relacionados ao projeto.

## Critérios de Aceitação

- [ ] Criar uma página inicial no pages que possua acesso aos outros documentos

**Comment by bielrossi15** [comment]
Pro pages, achei uns temas bem legais! Se interessar, aqui os links de como utilizá-los 

http://www.stephaniehicks.com/githubPages_tutorial/pages/githubpages-jekyll.html

https://help.github.com/articles/adding-a-jekyll-theme-to-your-github-pages-site-with-the-jekyll-theme-chooser/

http://jekyllthemes.org
