### ISSUE TITLE
Criar Quadro de Riscos

### ISSUE THREAD

**Issue by mateusvroriz** [fga-eps-mds/2018.2-CarDefense#19]
## Descrição da Tarefa
Para uma melhor gestão do projeto é necessário que se crie um quadro de riscos do projeto.

## Critérios de Aceitação

- [x] Listar Riscos
- [x] Listar Impacto dos Riscos
- [x] Listar Ação preventiva
- [x] Listar Ação reativa

**Comment by victorcmoura** [comment]
O Google Drive tem boas ferramentas de gráfico pra criar um burndown de riscos:
![image](https://user-images.githubusercontent.com/26290053/44869306-ac76b280-ac63-11e8-8d35-f4caf8b046cb.png)
Esse foi o resultado que o meu grupo conseguiu por lá. Deu pra automatizar as planilhas e tal, ficou bem fácil de usar
