### ISSUE TITLE
Elaborar protótipo de Baixa Fidelidade

### ISSUE THREAD

**Issue by bielrossi15** [fga-eps-mds/2018.2-CarDefense#25]
## Descrição da Tarefa
É necessário que a equipe de desenvolvedores de MDS elaborem o Protótipo de Baixa Fidelidade

## Critérios de Aceitação
- [x] Elaborar as partes separadas do protótipo com a equipe
- [x] Juntar as partes e montar o protótipo

**Comment by flyerjohn** [comment]
As partes separadas ja foram criadas, agora precisamos fazer a união.

**Comment by lievertom** [comment]
Todos desenhos estão prontos, agora tem que recortar e fazer slides?

**Comment by lucassoaresouza** [comment]
Só corte e os digitalize (ou corte a imagem gerada após a digitalização) dai a gente monta um doc com o passo a passo da aplicação.
