### ISSUE TITLE
CRUD de Automóveis

### ISSUE THREAD

**Issue by mateusvroriz** [fga-eps-mds/2018.2-CarDefense#42]
| | CRUD de Automóveis                                     |
|------|-------------------------------------------------------------|
| Eu como | Desenvolvedor|
| Desejo | Criar um CRUD de automóveis |
| Para/Pois | Poder cadastrar informações dos automóveis no sistema |

## Dependências
Não há 

## Critérios de aceitação

- [ ] Cadastrar Placa do carro
- [ ] Cadastrar Modelo do carro
- [ ] Cadastrar Cor do carro

## Comentário
.

**Comment by lucassoaresouza** [comment]
Colocar essa issue no template de User History.

**Comment by mateusvroriz** [comment]
Pronto, feito

**Comment by bielrossi15** [comment]
O commit deve ser feito com todo o conteudo da pasta, certo?

**Comment by bielrossi15** [comment]
Crud foi commitado

**Comment by flyerjohn** [comment]
Sim, a pasta inteira é commitada, o que importa é o que há de novo nela.

**Comment by lucassoaresouza** [comment]
Esse crud não fará parte do projeto final entretanto serve de treino de 'gitflow' para a equipe de desenvolvimento.
