### ISSUE TITLE
Crud de Usuários 

### ISSUE THREAD

**Issue by mateusvroriz** [fga-eps-mds/2018.2-CarDefense#43]
| | CRUD de Automóveis                                     |
|------|-------------------------------------------------------------|
| Eu como | Desenvolvedor |
| Desejo | Criar um CRUD de Usuários|
| Para/Pois | Poder cadastrar informações dos Usuários no sistema |

## Dependências
Não há 

## Critérios de aceitação

- [x] Cadastrar nome do usuário
- [x] Cadastrar email do usuário

## Comentário
.

**Comment by lucassoaresouza** [comment]
Colocar essa issue no template de User History.

**Comment by mateusvroriz** [comment]
Pronto, feito

**Comment by lucassoaresouza** [comment]
Esse crud não fará parte do projeto final entretanto serve de treino de 'gitflow' para a equipe de desenvolvimento.
