### ISSUE TITLE
CRUD de Avisos

### ISSUE THREAD

**Issue by mateusvroriz** [fga-eps-mds/2018.2-CarDefense#44]
| | CRUD de Automóveis                                     |
|------|-------------------------------------------------------------|
| Eu como | Desenvolvedor|
| Desejo | Criar um CRUD de avisos |
| Para/Pois | Poder cadastrar informações dos avisos no sistema |

## Dependências
Não há 

## Critérios de aceitação

- [x] Cadastrar nome do aviso 
- [x] Cadastrar tipo do aviso

## Comentário
.

**Comment by lucassoaresouza** [comment]
Colocar essa issue no template de User History.

**Comment by mateusvroriz** [comment]
Pronto, feito

**Comment by lucassoaresouza** [comment]
Esse crud não fará parte do projeto final entretanto serve de treino de 'gitflow' para a equipe de desenvolvimento.
