### ISSUE TITLE
Treinamento de React com 'Turma do APP'

### ISSUE THREAD

**Issue by lucassoaresouza** [fga-eps-mds/2018.2-CarDefense#50]
## Descrição da Tarefa
Para alinhar as quatro equipes responsáveis pelo 'app da FGA' haverá um treinamento de React geral para as quatro equipes.

## Critérios de Aceitação

- [ ] Treinamento sábado 08/09/2018

**Comment by lucassoaresouza** [comment]
Devido a dedetização da universidade na sexta feita dia 31/08/2018 o treinamento foi adiado para o dia 08/09/2018.

**Comment by bielrossi15** [comment]
Pra quem estiver precisando, achei um resumo de react muito bom!
https://www.devmedia.com.br/react-native-tutorial/32860

**Comment by bielrossi15** [comment]
Pra quem estiver precisando, achei um resumo de react muito bom!
https://www.devmedia.com.br/react-native-tutorial/32860

**Comment by stefanesouza** [comment]
Material que foi comentado no treinamento: 

* https://github.com/airbnb/enzyme -> Testes.
* https://redux.js.org - Redux
* https://www.udemy.com/desenvolvedor-multiplataforma-androidios-com-react-e-redux/?aff_code=Ewh3Y19bTXgDShx3MkBPbG1RGXFfVFh8CV4acU5TQHYBQBFxXT5XMRM%3D -> Curso do Udemy.

**Comment by lucassoaresouza** [comment]
O treinamento ocorreu  no dia 08/09/2018 das 9:30 as 12:00 horas.
