### ISSUE TITLE
Feedback Inicial - Issues e Documentação

### ISSUE THREAD

**Issue by fepas** [fga-eps-mds/2018.2-CarDefense#52]
Olá pessoas! A Carla me pediu pra dar um feedback dos grupos, e aqui estou! 

# CarDefense

- ## *Issues*

#### **Comunicação**

Vocês não estão se comunicando tanto pelas *issues*.

Se comunicar pelas *issues* trás uma comunicação bem transparente do projeto de vocês, e ajuda na avaliação de como vocês estão lidando com as adversidades de cada *issue*. É bem interessante que informações importantes estejam sempre sendo discutidas nas *issues*, além das outras ferramentas de comunicação que vocês usam, como *Telegram*.

#### **Pontuação**

Vocês não estão pontuando ainda as issues. É bem importante pontuar para que haja uma melhor forma de dividir as tarefas e planejar as sprints.
Aqui tem alguns links pra ajudar vocês ainda mais nisso:

- Detalhes sobre o método *Planning Poker*:

    http://www.metodoagil.com/planning-poker/

- Site para realizar o *Planning Poker* online:

    https://scrumpoker.online/

Eu particularmente prefiro fazer com *post-its*, mas vai da preferência da necessidade de cada grupo.

#### **Nomes**

As *issues* estão pouco padronizadas. É interessante a prática de padronizar os nomes, e vocês fazem em alguns casos, utilizando os verbos no infinitivo (que já seria a minha recomendação).

#### ***Labels***

As Labels não estão boas no geral. Estão um pouco vagas, não estão cumprindo o papel de definir a issue. Provavelmente eu faça um mini-guia para ajudar os grupos em relação á isso.

As issues de vocês possuem problemas, mas ainda dá tempo de mudar! (◕‿◕✿)

- ## Documentação

Não consegui achar nenhuma documentação de vocês. .·´¯`(>▂<)´¯`·.

- ## Considerações Finais

Vocês tem que melhorar as Issues de vocês e as documentações, não sei se ainda não estão prontas, ou não estão no repositório, mas isso é preocupante.
A Carla vai poder dar um feedback mais técnico pra vocês, mas espero ter ajudado na melhoria do
projeto de vocês de alguma forma. ( ⌒o⌒)人(⌒-⌒ )

[]s, @fepas

**Comment by lucassoaresouza** [comment]
Feedback recebido! Muito obrigado. Sobre a documentação: ela só não foi upada pro Pages pq ainda não definimos um tema lá. Já sobre as Issues estamos com um pouco de problemas mesmos mas estamos tentando resolver. Você, por gentileza, poderia nos falar quais problemas além dos que já citou nós temos nas Issues? Desde já obrigado!

**Comment by lucassoaresouza** [comment]
Valeu @fepas ! 
Grande parte do nosso vacilo está sendo em não trazer as informações para o github. A gente já tem o sistema de ponto certinho e também as issues pontuadas mas não fizemos a migração pra cá. Por isso entendo que já que não está aqui não temos kkk

**Comment by stefanesouza** [comment]
Já estamos trabalhando na questões das Labels, Issues e Nomes. A documentação também está toda no pages: https://fga-eps-mds.github.io/2018.2-CarDefense/docs/.
