### ISSUE TITLE
Trasferir documentos do Drive para o Pages

### ISSUE THREAD

**Issue by lucassoaresouza** [fga-eps-mds/2018.2-CarDefense#61]
## Descrição da Tarefa
É necessário que os documentos presentes no google drive sejam transferidos para o pages.

## Critérios de Aceitação

- [x] Transferir documento de visão
- [x] Transferir documento de arquitetura
- [x] Transferir burndown por sprint
- [x] Transferir velocity por sprint
- [x] Protótipo de baixa fidelidade

**Comment by bielrossi15** [comment]
Os docs serao transferidos em markdown ou html?

**Comment by darmsDD** [comment]
Qual a urgência dessa transferência?

**Comment by stefanesouza** [comment]
Será tudo em HTML e precisa ser feito o quanto antes.

**Comment by lievertom** [comment]
O documento de arquitetura foi transferido

**Comment by flyerjohn** [comment]
Os tópicos 4 ao 6 acabaram de serem adicionados ao documento de visão.

**Comment by rjoao** [comment]
O documento de visão foi transferido.

**Comment by lucassoaresouza** [comment]
Galera, eu preciso que vcs preencham o quadro de conhecimento para poder fazer a transferencia dos docs...
