### ISSUE TITLE
Estudar testes unitários em django

### ISSUE THREAD

**Issue by lucassoaresouza** [fga-eps-mds/2018.2-CarDefense#62]
## Descrição da Tarefa
É necessário que se estude como se produz testes unitários no framework Django.

## Critérios de Aceitação

- [x] Estudo de testes unitários em django

**Comment by PauloVitorRocha** [comment]
Tem alguma material interessante de apoio?

**Comment by bielrossi15** [comment]
Eu acho que a própria doc do django é interessante
https://docs.djangoproject.com/pt-br/2.1/internals/contributing/writing-code/unit-tests/

**Comment by bielrossi15** [comment]
Mais alguns links:
https://www.youtube.com/watch?v=TzCWadHwdSs
https://www.youtube.com/watch?v=WWa4bzTJZgI (muito bom!)

**Comment by PauloVitorRocha** [comment]
A documentação é muito boa! E ainda é traduzida

**Comment by bielrossi15** [comment]
E para escrever os testes, leiam essa patte especifica da doc:
https://docs.djangoproject.com/pt-br/2.1/topics/testing/overview/
