### ISSUE TITLE
Criar protótipo de alta fidelidade

### ISSUE THREAD

**Issue by lucassoaresouza** [fga-eps-mds/2018.2-CarDefense#63]
## Descrição da Tarefa
É necessário que, utilizando o protótipo de baixa fidelidade, se construa o protótipo de alta fidelidade utilizando uma ferramenta adequada para tal.

## Critérios de Aceitação

- [ ] Construir protótipo de alta fidelidade do sistema
- [ ] Demonstrar fluxos de uso do sistema

**Comment by lucassoaresouza** [comment]
Fluxos do sistema: cadastro de carro do usuário, aviso pessoal e aviso 'urgente'

**Comment by tayh** [comment]
No trabalho de IHC que eu fiz protótipos de alta fidelidade usando a ferramenta Quant-UX, é uma ferramenta muito boa e com muitas funcionalidades. Pra quem quiser dá uma olhada:

https://github.com/tayh/geekies/wiki/Prot%C3%B3tipo-de-Alta-Fidelidade
https://www.quant-ux.com

**Comment by tayh** [comment]
Eu acho uma das melhores que tem grátis, e você consegue simular os fluxos do aplicativo. Porém, ela pode ser um pouco complexa. Mas se tiverem outra melhor, não tem problema. xD

**Comment by stefanesouza** [comment]
Dica de site para a prototipação: https://marvelapp.com e para o fluxo dentro do app: https://www.invisionapp.com/
