### ISSUE TITLE
Feedback EPS

### ISSUE THREAD

**Issue by victorcmoura** [fga-eps-mds/2018.2-CarDefense#67]
# Feedback EPS

Salve, pessoal! Dei uma olhada no repositório de vocês e tenho algumas considerações a fazer. 

## Transparência do trabalho
Tive dificuldades em acompanhar o que foi produzido até o momento, não encontrei nada na wiki ou numa pasta /docs no repositório mesmo. Essa fase de documentação é uma excelente oportunidade para ensinar MDS a trabalhar com Git. Resolver conflitos em documentos escritos pode ser menos complicado e menos impactante do que resolver conflitos em código, por exemplo. Tragam os trabalhos para o repositório as soon as possible. Além disso, a rastreabilidade das tarefas fica comprometida, não há pull requests relacionados à documentação e isso seria uma excelente prática para transparecer e rastrear os artefatos produzidos.

Qualquer dúvida, podem me procurar. Abraços! =)

**Comment by victorcmoura** [comment]
Coloca o link do pages na descrição do repo xD
![image](https://user-images.githubusercontent.com/26290053/45521298-b46e4080-b793-11e8-94c4-58de54abad79.png)

**Comment by lucassoaresouza** [comment]
Aqui vai o link do pages: https://fga-eps-mds.github.io/2018.2-CarDefense/docs/
Assim que possível você poderia nos dar um feedback sobre nossa documentação?
Desde já, obrigado.

**Comment by victorcmoura** [comment]
Opa, dei uma olhada no pages de vcs e tenho algumas considerações:

- O card que levaria pro doc de viabilidade técnica na verdade ta levando pra metodologia
- O card que levaria para "especificação" na verdade ta levando pro doc de visão
- Ta, agora eu vi que as duas issues acima são mais um problema de usabilidade do que de links mesmo. Me perdi um pouco na navegação do pages de vocês kkk Seria legal ter uma index pra cada um dos tópicos e, a partir dela, ter o acesso aos docs em si.
- TAP cumpre com o objetivo
- Olhando o resultado de uma sprint, fiquei com uma dúvida. O burndown de vocês ta sendo feito na mão? Usem o ZenHub, é mais preciso (a issue fecha com o PR) e mais fácil pra vocês.
- Pela EAP, parece que tem muito mais trabalho de estudo e gerência pra fazer do que de desenvolvimento em si. Acho que da pra granularizar mais as tarefas de desenvolvimento ou generalizar mais as demais. Outra opção é aumentar o escopo, mas não sei se é o caso. Além disso, o cliente deve validar a EAP, caso vocês tenham um diretamente.
- Achei meio estranho o pipeline de deploy, mais precisamente na parte onde tem uma seta do kubernetes para o guinicorn. Da a impressão de que a aplicação passa pelo kubernetes, não necessariamente fica lá, e vai para o guinicorn. (Aproveito o gancho da conversa sobre pipeline/devops pra oferecer qualquer orientação técnica em relação a docker, ferramentas de CI/CD, etc)

Sobre os papéis no doc de metodologia, não tem nada errado ali, mas seria legal vcs terem uma noção mais de objetivo geral (não precisa necessariamente colocar no doc, mas é bom vcs saberem):

- **Arquiteto**: Prever possíveis desafios técnicos e levantar a solução ideal para, quando chegar no momento de implementar, ja ter tudo encaminhado.
- **DevOps**: Além de manter os pipelines e tudo mais, ele deve disseminar a cultura de entrega contínua no time. Se ele enxergar algum gargalo que esteja impedindo isso, deve levantar a mão e avisar ao resto do time.
- **PO**: Orquestrar todas as decisões do time sempre levando em consideração a opinião dos stakeholders. As decisões vão desde a prioridade do backlog até na maneira como os pipelines de deploy acontecem (deve ter deploy em produção toda sprint ou sempre que a feature ficar pronta? Deve ter mais de um ambiente de deploy? Onde o deploy deve ficar? etc).
- **Scrum Master**: Exatamente o que está no doc de vocês. O SM deve viabilizar a metodologia ao máximo.

Lembro que qualquer melhoria ou sugestão pode, e deve, partir de qualquer membro do time. Não engessem os papeis e as decisões só pq eu falei isso aqui pra vcs kkkkk

É isso galera, minha única preocupação em relação ao time de vocês é a quantidade de código mesmo. Me parece levemente atrasado nesse aspecto =S

Bom trabalho a todos! =)

**Comment by lucassoaresouza** [comment]
Muítissimo obridado, @victorcmoura ! Vamos pegar todas as suas considerações e fazer uma revisão completa tanto to pages quanto dos docs.
Falando rapidamente sobre o burndow: já começamos a cria-lo pelo zenhub e, inclusive, tivemos problemas nessa ultima sprint (erro nosso mesmo).
Mas uma vez muito obrigado!

**Comment by victorcmoura** [comment]
Ah, tranquilo. Que bom que resolveram =D Vou fechar a issue para manter a organização. Qualquer coisa so abrir outra.
