### ISSUE TITLE
Fazer Estudos de Metodologia

### ISSUE THREAD

**Issue by lucassoaresouza** [fga-eps-mds/2018.2-CarDefense#7]
### Descrição da Tarefa
É necessário que a equipe de desenvolvimento estude sobre as metodologias ágeis (Scrum e XP).

## Critérios de Aceitação

- [x] Efetuar estudo de Scrum
- [x] Efetuar estudo de XP

**Comment by stefanesouza** [comment]
Materiais sugeridos por EPS para estudo:

SCRUM:
https://www.desenvolvimentoagil.com.br/scrum/
https://www.youtube.com/watch?v=XfvQWnRgxG0

XP:
https://www.devmedia.com.br/extreme-programming-conceitos-e-praticas/1498
http://www.desenvolvimentoagil.com.br/xp/
https://www.youtube.com/watch?v=ALvpFMcL-dI
