### ISSUE TITLE
Notificações

### ISSUE THREAD

**Issue by stefanesouza** [fga-eps-mds/2018.2-CarDefense#73]
Eu, como usuário, desejo criar e enviar notificações públicas e privadas.

**Comment by bielrossi15** [comment]
Sobre material de apoio, achei uma serie de videos sobre nosso front de react e firebase! 

https://www.youtube.com/watch?v=KnwfK807Mgc&list=PLy9JCsy2u97m-xWAxGwHZ2vITtj4qBKDm

**Comment by lucassoaresouza** [comment]
Conversando com a galera aqui fui informado de que poderíamos fazer as notificações usando o firebase entretanto parece q é possível utilizar o expo também.
