### ISSUE TITLE
Enviar Notificações sobre o Carro

### ISSUE THREAD

**Issue by stefanesouza** [fga-eps-mds/2018.2-CarDefense#75]
|  | Enviar Notificações sobre o Carro                                     |
|------|-------------------------------------------------------------|
| Eu como | desenvolvedor |
| Desejo | enviar notificações sobre o carro |
| Para/Pois | que o usuário seja informado em tempo real |

## Dependências
- [x] [#74 Criar Notificações sobre o Carro](https://github.com/fga-eps-mds/2018.2-CarDefense/issues/74)

## Critérios de Aceitação
- [x] Deve possuir os testes;
- [x] Deve estar configurada com o front-end;
- [x] A notificação deve ser enviada apenas para o dono do veículo cadastrado pela placa;
- [x] A notificação precisa chegar de modo instantâneo

**Comment by bielrossi15** [comment]
Sobre as notificacoes, existe uma sessao muito boa na doc do expo feito pra enviar e receber notificacoes no front-end: 
https://docs.expo.io/versions/latest/guides/push-notifications
