### ISSUE TITLE
Configurar Ambiente de Homologação e Produção[divida]

### ISSUE THREAD

**Issue by stefanesouza** [fga-eps-mds/2018.2-CarDefense#79]
## Descrição da Tarefa
É necessário que o ambiente de homologação e o de produção do projeto sejam criados e configurados.

## Critérios de Aceitação

- [x] Ambiente de Homologação
- [x] Ambiente de Produção

**Comment by tayh** [comment]
Configuração dos ambientes foram atrasadas por causa da configuração do Rancher que estava dando problema,  a seguir os links dos microsserviços já configurados para produção escolhidos para serem apresentados na R1.

Microsserviço de notificação: http://68.183.28.199:8002/
Microsserviço de profile: http://68.183.28.199:8005/
