### ISSUE TITLE
Fazer Estudos de GIT

### ISSUE THREAD

**Issue by lucassoaresouza** [fga-eps-mds/2018.2-CarDefense#8]
## Descrição da Tarefa
É necessário que a equipe de desenvolvimento estude a ferramenta de versionamento Git

## Critérios de Aceitação
- [x] Efetuar estudo de Git

**Comment by stefanesouza** [comment]
Materiais sugeridos por EPS para estudo: 

GIT:
https://git-scm.com/book/en/v2/Getting-Started-Git-Basics
https://git-scm.com/book/pt-br/v1/Primeiros-passos-No%C3%A7%C3%B5es-B%C3%A1sicas-de-Git(pt-br)
https://www.codecademy.com/learn/learn-git
