### ISSUE TITLE
Configurar o ambiente Rancher 2.0 

### ISSUE THREAD

**Issue by mateusvroriz** [fga-eps-mds/2018.2-CarDefense#88]
## Descrição da Tarefa
Configurar o ambiente Rancher 2.0 para o projeto utilizando o sistema de orquestração de containers Kubernetes e hospendando o sistema no Digital Ocean.

## Critérios de Aceitação

- [x] Criar um ambiente Rancher 2.0
- [x] Subir as imagens do DockerHub para o workload do Rancher

**Comment by tayh** [comment]
As orquestrações foram feitas com o Rancher 1.6, e a seguir os links dos microsserviços já configurados para produção escolhidos para serem apresentados na R1.

Microsserviço de notificação: http://68.183.28.199:8002/
Microsserviço de profile: http://68.183.28.199:8005/

**Comment by tayh** [comment]
A pipline pode ser vista em: https://fga-eps-mds.github.io/2018.2-CarDefense/docs/docarquitetura.html
