### ISSUE TITLE
Fazer Quadro de Conhecimento

### ISSUE THREAD

**Issue by lucassoaresouza** [fga-eps-mds/2018.2-CarDefense#9]
## Descrição da Tarefa
É necessário que seja criado um quadro de conhecimentos para que se possa medir o crescimento do conhecimento da equipe de sprint em sprint

## Critérios de Aceitação

- [x] Os campos do quadro devem conter todas as ferramentas e técnicas utilizadas para a produção do projeto

**Comment by stefanesouza** [comment]
Quadro de Conhecimento: [Clique aqui para acessar](https://drive.google.com/open?id=11nFmc-68aBTFpjeZvSd12fkpYNtq1bXnyhNDu1sZnzk)
