### ISSUE TITLE
Implementar validações nos campos de notificações privadas

### ISSUE THREAD

**Issue by stefanesouza** [fga-eps-mds/2018.2-CarDefense#97]
O que deve ser feito:
- Deve ter validações de situações como: campo em branco, passar do número de caracteres permitidos, ter menos caracteres do que é necessário (exemplo: placa do carro), colocar campos como obrigatórios.

**Comment by bielrossi15** [comment]
Acho que ficaria melhor colocar um valor maximo em cada campo, ao inves de colocar uma validacao pra isso
